DROP DATABASE IF EXISTS test;
DROP DATABASE IF EXISTS  devises;
DROP DATABASE IF EXISTS  customers;
DROP DATABASE IF EXISTS  orders;
DROP DATABASE IF EXISTS  purchases;

CREATE DATABASE IF NOT EXISTS test;
CREATE DATABASE IF NOT EXISTS devises;
CREATE DATABASE IF NOT EXISTS customers;
CREATE DATABASE IF NOT EXISTS orders;
CREATE DATABASE IF NOT EXISTS purchases;

