#FROM docker.elastic.co/elasticsearch/elasticsearch:6.3.2
#FROM docker.elastic.co/elasticsearch/elasticsearch:6.8.6
FROM docker.elastic.co/elasticsearch/elasticsearch:7.5.1
# eventuelle config via elasticsearch.yml
