DROP DATABASE IF EXISTS  devises;
DROP DATABASE IF EXISTS  customers;
DROP DATABASE IF EXISTS  orders;
DROP DATABASE IF EXISTS  purchases;

CREATE DATABASE devises;
CREATE DATABASE customers;
CREATE DATABASE orders;
CREATE DATABASE purchases;

