version: '3'
 
services:
 elasticsearch:
   build : ./elasticsearch
   container_name: elasticsearch
   environment:
     - "discovery.type=single-node"
   networks:
     - net
   ports:
     - "9200:9200"
   volumes:
     - esdata:/usr/share/elasticsearch/data
 
 kibana:
   build : ./kibana
   container_name: kibana
   environment:
     SERVER_NAME : kibana
     ELASTICSEARCH_URL : http://elasticsearch:9200
   networks:
     - net
   ports:
     - "5601:5601"
 
 proxy:
   build : ./nginx
   container_name : proxy
   ports:
     - "8080:80"
   networks:
     - net
 
volumes:
   esdata:
     driver: local
 
networks:
   net: