version: '3'
 
services:
     
 registry:
   image : registry:2
   restart: always
   container_name: registry
   #ports:
   #  - "5000:5000"
   # en interne seulement (pas exposé , par sécurité)
   volumes:
     - "/srv/registry/data:/var/lib/registry"
 
 proxy:
   #only nginx:alpine image supports bcrypt
   image : nginx:alpine
   container_name : nginx-secure-proxy
   restart: always
   #command: [nginx-debug, '-g', 'daemon off;']
   ports:
     - "443:443"
     # :443 (ssl) for docker pull without login/basic_auth
     - "4443:4443"
     # :4443 (ssl) for docker push with login/basic_auth
   links:
     - registry
   volumes:
     # /srv/registry/security must contain copies of nginx.conf , 
     # registry.crt , registry.key and htpasswd  
     - "/srv/registry/security:/etc/nginx/conf.d"
     - "/srv/registry/security/nginx.conf:/etc/nginx/nginx.conf:ro"
 
 